---
title: "Article 1 : CRISPR enters its first human trials"
description: The CRISPR-Cas9 genome editing technique was discovered by a French researcher Emmanuelle Charpentier collaborating with an American Jennifer Doudna. This tools  allow modifying genome sequences with precision and open the way of new discoveries. Reseachers are working on different applications such as prevent or cure diseases.

author:
  - name: Hoegener Victor
date: 10-16-2019
preview: images/Crispr-Cas9.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| to get underway   | to start                   |
| to chop                    | to cut into pieces         |
| under way                    | in progress         |
| sickle-cell disease                    | inherited red blood cell disorders         |
| womb                    | uterus         |
| grab (sth) from                    | extract, take something         |
| harmless                    | inoffensive         |
| arguably                    | can be defended         |
| to shelve                    | to put (sth) aside, to abandon |
| to live up to (sth)                    | be as good as         |

## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Tina Hensman Saey, senior staff writer on molecular biology for ScienceNews                        |
| Published in?                | September 16, 2019                                                       |
| General topic?               |  The article shows the fields of study that employ the technology of Crispr-Cas 9. This method would cure hereditary diseases                      |
| What was examined?       |  Some animals were cured thanks to Crisper-Cas9 method. Now reseachers are making human trials to cure deseases. Firstly, the studies are trying to get a treatment for sickle-cell disease and beta-thalassemia. Simply, the scientists take the patient's sick cells and Crisper-Cas9 edits the genome of the cells, the edited cells return to the sick patient. Two patients have already received a treatment. Another way of working but much more difficult is to edit cells into the body. Editas Medicine of Cambridge works on the gene known as CEP290, responsible for blindness.      |
| Conclusions/discovery?       |  This technology has yet to prove conclusive results      |
| Remaining questions?         | how far can we go to modify the human genome? |


<https://www.sciencenewsforstudents.org/article/crispr-enters-its-first-human-trials>
