---
title: "Article 3 : Gene Editing Humans: It's Not Just about Safety"
description: |
  In november 2018, He Jiankui, a chinese scientist shocked the world editing two embryos and letting them grow. A community of scientists got together to fix guidelines for human germ line editing that scientists have to follow.
author:
  - name: Hoegener Victor
    url: {}
date: 11-16-2019
preview: images/gene_editing.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Vocabulary

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| renegade *adj*  | rebel                   |
| a framework *n*                   | system, basic structrue underlying a concept         |
| a bench *n*                    |  a long work table        |
| to blur *v*                    | to become indistinct         |
| intractable *adj*                    | hard to control, unmanageable         |
| likelihood *n*                    | probability         |
| to assert *v*                   | declare, speak in a confident manner         |
| to strive *n*                    | make great effort to         |
| to nurture (sb)                    | to protect while they are growing         |
| a long way off                    | far away         |
| a polling *n*                   | voting         |
| to sustain *v*                    | to support physically or mentally        |

## Analysis table

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | By Mildred Z. Solomon                        |
| Published in?                | August 20, 2019                                                       |
| General topic?               | The scientific community wants to set limits on the experiments made on the human germ line. Indeed, in the past two years, Chinese and Russian researchers have shocked the world by trying to manipulate human embryos.                      |
| What was examined?       | L'article aborde deux aspects, d'une part le développement de technologies permettant de modifier le génome, qui ne sont pas entièrement comprises et qui peuvent avoir des effets secondaires. D'autre part, l'impact de ces technologies sur les générations futures. C'est pourquoi les organisations se réunissent pour discuter de questions éthiques. Si nous parvenons à modifier la lignée germinale en toute sécurité, l’humanité voudra l’appliquer de manière malsaine. Par exemple, il sera possible de "renforcer" l'humanité telle que nous la souhaitons. Comme Michael Sandel de l’Université de Harvard a déclaré "nous perdrions le sens des enfants comme des cadeaux à nourrir au fur et à mesure qu’ils viennent à nous et les considérons plutôt comme des objets que nous avons conçus". Si le sujet fait débat, c'est parce qu'il faut sensibiliser la population des implications de ces nouvelles technologies.     |
| Conclusions/discovery?       | Collective work is important to make these technologies safer.       |
| Remaining questions?         | how to solve the ethical problems related to these technologies for the future?       |


<https://blogs.scientificamerican.com/observations/gene-editing-humans-its-not-just-about-safety/>


