---
title: "Article 4 : Scientists Program CRISPR to Fight Viruses in Human Cells"
description: |
  Crisper-Cas13 is a promising method to fight against viruses such as Ebola or influenza. 
author:
  - name: Hoegener Victor
    url: {}
date: 11-28-2019
preview: images/viruse_influenza.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Vocabulary

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| a strand *n*  | a thread                   |
| to encounter (sth) or (sb) *v*                   | to meet unexpectedly         |
| Cas 9 *n*                    |  a Crisper enzyme which makes a cut in the double-stranded DNA        |
| Cas 13 *n*                    | a Crisper enzyme which can cleave single-stranded RNA         |
| to rely on *v*                    | to depend on         |
| the flu *n*                    | abbreviation for the viruse influenza         |
| twoflod *adj*                   | double, by two         |
| to make (sb) tick *v*                    | to motivate, inspire (sb)         |


## Analysis table

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | By Tanya Lewis, an associate editor at Scientific American                         |
| Published in?                | October 23, 2019                                                       |
| General topic?               | Reseachers study the operation of Crisper-Cas 13 system to discover new antiviral therapies. The mechanism comes from the way that bacteriophages denfend against viruses.                      |
| What was examined?       | 
     |
| Conclusions/discovery?       | The biggest advantage of crisper is that we can program it as we want. Cas9 can be used to determine the amount of remaining virus that can infect other cells. But most important, it can target a virus using several guide RNAs.
       |
| Remaining questions?         | How to use Cripser-Cas13 to treat a living person from a viruse? How should we respond if the virus develops resistance against treatment?       |



<https://www.scientificamerican.com/article/scientists-program-crispr-to-fight-viruses-in-human-cells/>
