---
title: "Article 2 : What your DNA Can't tell you"
description: |
  A short description of the post.
author:
  - name: Hoegener Victor
    url: {}
date: 10-28-2019
preview: images/genome-banner.png
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

What Your DNA Can’t Tell You

Companies are selling reports about a wide range of physical, cognitive, and behavioral traits to consumers based on their genomic data, but such tests have a number of limitations.


“Upload DNA data and know more about yourself,” promises Genomelink, anywhere from fitness-related attributes, such as longevity, pulmonary function, and job-related exhaustion, to intelligence-associated characteristics, including mathematical ability, hippocampal volume, and educational attainment. Just send over your data obtained from DNA testing companies such as 23andMe, Ancestry, or My Heritage and the California-based company will send back insight into more than 125 traits.

There are several other companies that provide consumers with reports about physical, cognitive, and behavioral traits based on their DNA data. Some, like GenePlaza, Helix, and Sequencing.com, have launched genetic app stores where users can choose from a variety of products. The cost of these tests varies significantly: The most expensive app on GenePlaza is €6 ($6.50 US), while Helix’s range from free to more than $200. For $14 a month, Genomelink sends users one new trait report per week.

To generate trait reports, these companies typically compare a user’s DNA to data harnessed from published genome-wide association studies (GWAS). Want to know about your propensity for loneliness? Genomelink uses data from a 2018 Nature Communications study that examined this trait in more than 450,000 UK Biobank participants. Genomic researchers are constantly publishing new findings, says Tomohiro Takano, one of Genomelink’s founders. “So when we started Genomelink, we were wondering, how can we bring the positive and entertaining side of science directly to consumers?”

While direct-to-consumer (DTC) trait tests may be increasingly popular, their utility remains an open question. “There are many layers of unvalidated science,” says Catherine Bliss, a sociologist at the University of California, San Francisco. “[Consumers] get a lot less reliable information than they think they’re getting.”

**The limits of GWAS**

GWASs allow scientists to estimate the combined effects of single nucleotide polymorphisms to generate polygenic scores, which provide an estimate of how likely it is that an individual will develop a certain trait. Polygenic scores are widely used in scientific research, but they come with a number of limitations that are important to consider in the context of DTC tests.

There are two key issues when it comes to predicting traits with DNA data, according to Daniel Benjamin, a behavioral economist at the University of Southern California. One is that there is very little scientific evidence to support predictions for certain phenotypes, including many associated with fitness or parenting behaviors. On the other hand, even for traits that scientists have carefully examined in large GWASs, such as educational attainment, polygenic scores are typically only useful for predicting differences between groups. “That’s what makes them useful in research,” Benjamin explains. “But for the purpose of predicting what any particular individual’s phenotype is going to be, the predictive power is very low.”

To prevent people from misunderstanding the data from their own GWASs on cognitive and behavioral characteristics, Benjamin and his colleagues in the Social Science Genetic Association Consortium (SSGAC) set up a detailed FAQ page to accompany their papers. People often misinterpret the idea that genetic factors are associated with certain traits as meaning that they explain intrinsic biological differences in ability, Benjamin says. But genetic factors can matter for purely social and environmental reasons. For example, if scientists tried to predict educational attainment from DNA during a period when females faced greater barriers to obtaining schooling, the number of X chromosomes would likely be one of the strongest predictors of education attainment—due to circumstance, not biology.

In addition, most of the large GWASs have been conducted in individuals of European descent. For this reason, it’s not yet clear whether the results will be relevant for other populations, says Andrea Ganna, a geneticist at the Institute for Molecular Medicine Finland. On top of that, large datasets in the UK, such as the UK Biobank, have dominated these studies, Ganna adds. “So how this work translates to other populations, even within Europe, is an [open] question.”

Tests for traits like intelligence come with the added issue of potential ethical and societal implications. “There’s two schools of concerns,” says Yaniv Erlich, the co-creator of DNA.Land, a research-project-turned-independent-company that provides free trait reports to consumers. “One is that we predict intelligence so badly that the reports are useless. The other is we can predict it so well that people can start to discriminate based on these reports.” While the field is currently facing the former problem, according to Bliss, there are already people, including some scientists and educators, who see the utility in using such tests to guide children’s futures.

**Maintaining transparency, educating consumers**

Given these shortcomings, why provide such tests at all? “At this point, we are purely focusing on the user having a positive, fun experience—we are not asking users to take any action,” says Genomelink’s Takano. “My philosophy is that, the information is already available, so rather than hiding that, we want to try to educate people so that they can understand the limitation of the science.”

Takano says that his company tries to be as transparent as possible to its consumers. Its trait reports come with “scientific reliability” ratings based on the robustness of the reference literature, as well as a description of the underlying research. Genomelink also provides a brief explanation on the FAQ page about how limitations in the science may lead to inaccurate results. (A more in-depth description is provided in an accompanying blog post.)

Other companies also provide consumers with information about their products’ limitations. Geneplaza, whose apps include reports about ancestry, intelligence, and same sex attraction, has a disclaimer on most of its apps, along with some information about the underlying science. “We try to stress the fact that this is not a disposition score, it’s not a diagnostic,” says Alain Coletta, cofounder and CEO of GenePlaza. “We hope we’re doing a good enough job but it’s not easy to do.”

Erlich notes that he and his colleagues at DNA.Land chose to primarily provide reports for physical features, such as height and eye color, so that people could easily verify whether or not the genetic predictions were correct. On the other hand, he adds, they launched their intelligence report to have the opposite effect. “We aim to show you that we cannot predict intelligence in any meaningful way,” says Erlich, who is now the chief scientific officer at MyHeritage. “Right now, [these reports are] more just for entertainment and to understand the limitations. I think the main benefit is engaging people with genetic research.”

In principle, if consumers understand the limitations of polygenic scores, finding out your genetic prediction for a given trait could be a fun activity, Benjamin says. “But my worry is that they won’t understand the information they’ve been given.” He adds that one thing that’s currently missing is research into how best to present these types of disclaimers, and how well people comprehend this information when it’s presented clearly. “It’s a good thing that these companies have disclaimers, but it’s not enough,” Benjamin tells The Scientist. “People have to actually understand the information.”

## Vocabulary

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| exhaustion   | extreme tiredness                   |
| attainment                    | achievement, act of attaining         |
| to provide (sth)                    | to supply, to furnish         |
| to harness (sth)                    | to make use of (sth)         |


## Analysis table

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | DIANA KWON, a freelance journalist based in Berlin                        |
| Published in?                | October 2, 2019                                                       |
| General topic?               |                        |
| What was examined?       |        |
| Conclusions/discovery?       |        |
| Remaining questions?         |        |

<https://www.the-scientist.com/news-opinion/what-your-dna-cant-tell-you-66523>
